package ria.ordermanagement.events;

public enum OrderEventType {
    SEARCH_BUTTON_PRESSED, CREATE_BUTTON_PRESSED, EDIT_ORDER_SELECTED, CANCEL_EDIT_BUTTON_PRESSED, SAVE_EDIT_BUTTON_PRESSED, INIT_ORDERS_SEARCH
}
